M48
; DRILL file {KiCad 9.0.4} date 2026-01-03T14:11:34-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-03T14:11:34-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X151.297Y-72.174
X156.297Y-72.174
T2
X96.393Y-115.443
X96.436Y-128.905
M30
