M48
; DRILL file {KiCad 6.0.1-79c1e3a40b~116~ubuntu20.04.1} date Thu 20 Jan 2022 03:32:32 PM EST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-01-20T15:32:32-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.1-79c1e3a40b~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1181
%
G90
G05
T1
X8.062Y-3.3726
T2
X4.4059Y-3.385
X4.905Y-4.4541
X9.0933Y-4.26
T0
M30
